
// Code generated by stanc b0a4f0db
#include <stan/model/model_header.hpp>
namespace normal_mixture_k_prop_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 

stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 8, column 2 to column 19)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 9, column 2 to column 21)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 10, column 2 to column 14)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 11, column 2 to column 25)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 12, column 2 to column 25)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 15, column 2 to column 16)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 17, column 2 to column 52)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 42, column 0 to column 9)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 43, column 0 to column 11)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 44, column 0 to column 20)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 45, column 0 to column 24)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 47, column 0 to column 8)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 51, column 8 to line 52, column 56)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 50, column 21 to line 53, column 7)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 50, column 6 to line 53, column 7)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 54, column 6 to column 29)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 49, column 15 to line 55, column 5)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 49, column 0 to line 55, column 5)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 21, column 2 to column 23)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 22, column 2 to column 25)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 23, column 2 to column 22)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 27, column 12 to column 13)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 27, column 4 to column 15)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 28, column 11 to column 12)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 28, column 4 to column 24)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 29, column 4 to column 28)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 33, column 8 to line 34, column 51)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 32, column 21 to line 35, column 7)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 32, column 6 to line 35, column 7)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 36, column 6 to column 32)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 31, column 19 to line 37, column 5)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 31, column 4 to line 37, column 5)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 26, column 2 to line 38, column 3)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 2, column 2 to column 17)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 3, column 2 to column 17)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 4, column 9 to column 10)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 4, column 2 to column 12)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 5, column 9 to column 10)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 5, column 2 to column 19)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 8, column 10 to column 11)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 9, column 10 to column 11)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 12, column 22 to column 23)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 15, column 10 to column 11)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 43, column 8 to column 9)",
                                                      " (in 'org/normal_mixture_k_prop/normal_mixture_k_prop.stan', line 44, column 7 to column 8)"};



class normal_mixture_k_prop_model final : public model_base_crtp<normal_mixture_k_prop_model> {

 private:
  int K;
  int N;
  std::vector<double> y;
  Eigen::Matrix<double, -1, 1> z_test;
 
 public:
  ~normal_mixture_k_prop_model() { }
  
  inline std::string model_name() const final { return "normal_mixture_k_prop_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 b0a4f0db", "stancflags = "};
  }
  
  
  normal_mixture_k_prop_model(stan::io::var_context& context__,
                              unsigned int random_seed__ = 0,
                              std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "normal_mixture_k_prop_model_namespace::normal_mixture_k_prop_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 34;
      context__.validate_dims("data initialization","K","int",
          context__.to_vec());
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 34;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 34;
      current_statement__ = 34;
      check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 35;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 35;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 35;
      current_statement__ = 35;
      check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 36;
      validate_non_negative_index("y", "N", N);
      current_statement__ = 37;
      context__.validate_dims("data initialization","y","double",
          context__.to_vec(N));
      y = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 37;
      assign(y, nil_index_list(), context__.vals_r("y"),
        "assigning variable y");
      current_statement__ = 38;
      validate_non_negative_index("z_test", "N", N);
      current_statement__ = 39;
      context__.validate_dims("data initialization","z_test","double",
          context__.to_vec(N));
      z_test = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(z_test, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> z_test_flat__;
        current_statement__ = 39;
        assign(z_test_flat__, nil_index_list(), context__.vals_r("z_test"),
          "assigning variable z_test_flat__");
        current_statement__ = 39;
        pos__ = 1;
        current_statement__ = 39;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 39;
          assign(z_test, cons_list(index_uni(sym1__), nil_index_list()),
            z_test_flat__[(pos__ - 1)], "assigning variable z_test");
          current_statement__ = 39;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 40;
      validate_positive_index("theta", "K", K);
      current_statement__ = 41;
      validate_positive_index("mu_prop", "K", K);
      current_statement__ = 42;
      validate_non_negative_index("sigma", "K", K);
      current_statement__ = 43;
      validate_non_negative_index("mu", "K", K);
      current_statement__ = 44;
      validate_non_negative_index("ps", "K", K);
      current_statement__ = 45;
      validate_non_negative_index("log_theta", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += (K - 1);
      num_params_r__ += (K - 1);
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += K;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "normal_mixture_k_prop_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> theta;
      theta = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(theta, DUMMY_VAR__);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> theta_in__;
      theta_in__ = Eigen::Matrix<local_scalar_t__, -1, 1>((K - 1));
      stan::math::fill(theta_in__, DUMMY_VAR__);
      
      current_statement__ = 1;
      theta_in__ = in__.vector((K - 1));
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        assign(theta, nil_index_list(),
          stan::math::simplex_constrain(theta_in__, lp__),
          "assigning variable theta");
      } else {
        current_statement__ = 1;
        assign(theta, nil_index_list(),
          stan::math::simplex_constrain(theta_in__),
          "assigning variable theta");
      }
      Eigen::Matrix<local_scalar_t__, -1, 1> mu_prop;
      mu_prop = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(mu_prop, DUMMY_VAR__);
      
      Eigen::Matrix<local_scalar_t__, -1, 1> mu_prop_in__;
      mu_prop_in__ = Eigen::Matrix<local_scalar_t__, -1, 1>((K - 1));
      stan::math::fill(mu_prop_in__, DUMMY_VAR__);
      
      current_statement__ = 2;
      mu_prop_in__ = in__.vector((K - 1));
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        assign(mu_prop, nil_index_list(),
          stan::math::simplex_constrain(mu_prop_in__, lp__),
          "assigning variable mu_prop");
      } else {
        current_statement__ = 2;
        assign(mu_prop, nil_index_list(),
          stan::math::simplex_constrain(mu_prop_in__),
          "assigning variable mu_prop");
      }
      local_scalar_t__ mu_loc;
      mu_loc = DUMMY_VAR__;
      
      current_statement__ = 3;
      mu_loc = in__.scalar();
      local_scalar_t__ mu_scale;
      mu_scale = DUMMY_VAR__;
      
      current_statement__ = 4;
      mu_scale = in__.scalar();
      current_statement__ = 4;
      if (jacobian__) {
        current_statement__ = 4;
        mu_scale = stan::math::lb_constrain(mu_scale, 0, lp__);
      } else {
        current_statement__ = 4;
        mu_scale = stan::math::lb_constrain(mu_scale, 0);
      }
      std::vector<local_scalar_t__> sigma;
      sigma = std::vector<local_scalar_t__>(K, DUMMY_VAR__);
      
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 5;
        assign(sigma, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable sigma");}
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 5;
        if (jacobian__) {
          current_statement__ = 5;
          assign(sigma, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(sigma[(sym1__ - 1)], 0, lp__),
            "assigning variable sigma");
        } else {
          current_statement__ = 5;
          assign(sigma, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(sigma[(sym1__ - 1)], 0),
            "assigning variable sigma");
        }}
      Eigen::Matrix<local_scalar_t__, -1, 1> mu;
      mu = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(mu, DUMMY_VAR__);
      
      current_statement__ = 7;
      assign(mu, nil_index_list(),
        add(mu_loc, multiply(mu_scale, cumulative_sum(mu_prop))),
        "assigning variable mu");
      current_statement__ = 6;
      current_statement__ = 6;
      check_ordered(function__, "mu", mu);
      {
        current_statement__ = 19;
        lp_accum__.add(cauchy_lpdf<propto__>(mu_loc, 0, 5));
        current_statement__ = 20;
        lp_accum__.add(cauchy_lpdf<propto__>(mu_scale, 0, 5));
        current_statement__ = 21;
        lp_accum__.add(cauchy_lpdf<propto__>(sigma, 0, 5));
        {
          current_statement__ = 22;
          validate_non_negative_index("ps", "K", K);
          std::vector<local_scalar_t__> ps;
          ps = std::vector<local_scalar_t__>(K, DUMMY_VAR__);
          
          current_statement__ = 24;
          validate_non_negative_index("log_theta", "K", K);
          Eigen::Matrix<local_scalar_t__, -1, 1> log_theta;
          log_theta = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
          stan::math::fill(log_theta, DUMMY_VAR__);
          
          current_statement__ = 26;
          assign(log_theta, nil_index_list(), stan::math::log(theta),
            "assigning variable log_theta");
          current_statement__ = 32;
          for (int n = 1; n <= N; ++n) {
            current_statement__ = 29;
            for (int k = 1; k <= K; ++k) {
              current_statement__ = 27;
              assign(ps, cons_list(index_uni(k), nil_index_list()),
                (log_theta[(k - 1)] +
                  normal_log<false>(y[(n - 1)], mu[(k - 1)], sigma[(k - 1)])),
                "assigning variable ps");}
            current_statement__ = 30;
            lp_accum__.add(log_sum_exp(ps));}
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "normal_mixture_k_prop_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      Eigen::Matrix<double, -1, 1> theta;
      theta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(theta, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<local_scalar_t__, -1, 1> theta_in__;
      theta_in__ = Eigen::Matrix<local_scalar_t__, -1, 1>((K - 1));
      stan::math::fill(theta_in__, DUMMY_VAR__);
      
      current_statement__ = 1;
      theta_in__ = in__.vector((K - 1));
      current_statement__ = 1;
      assign(theta, nil_index_list(),
        stan::math::simplex_constrain(theta_in__), "assigning variable theta");
      Eigen::Matrix<double, -1, 1> mu_prop;
      mu_prop = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(mu_prop, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<local_scalar_t__, -1, 1> mu_prop_in__;
      mu_prop_in__ = Eigen::Matrix<local_scalar_t__, -1, 1>((K - 1));
      stan::math::fill(mu_prop_in__, DUMMY_VAR__);
      
      current_statement__ = 2;
      mu_prop_in__ = in__.vector((K - 1));
      current_statement__ = 2;
      assign(mu_prop, nil_index_list(),
        stan::math::simplex_constrain(mu_prop_in__),
        "assigning variable mu_prop");
      double mu_loc;
      mu_loc = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      mu_loc = in__.scalar();
      double mu_scale;
      mu_scale = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      mu_scale = in__.scalar();
      current_statement__ = 4;
      mu_scale = stan::math::lb_constrain(mu_scale, 0);
      std::vector<double> sigma;
      sigma = std::vector<double>(K, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 5;
        assign(sigma, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable sigma");}
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 5;
        assign(sigma, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(sigma[(sym1__ - 1)], 0),
          "assigning variable sigma");}
      Eigen::Matrix<double, -1, 1> mu;
      mu = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(mu, std::numeric_limits<double>::quiet_NaN());
      
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(theta[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(mu_prop[(sym1__ - 1)]);}
      vars__.emplace_back(mu_loc);
      vars__.emplace_back(mu_scale);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(sigma[(sym1__ - 1)]);}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 7;
      assign(mu, nil_index_list(),
        add(mu_loc, multiply(mu_scale, cumulative_sum(mu_prop))),
        "assigning variable mu");
      current_statement__ = 6;
      current_statement__ = 6;
      check_ordered(function__, "mu", mu);
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          vars__.emplace_back(mu[(sym1__ - 1)]);}
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      double lik;
      lik = std::numeric_limits<double>::quiet_NaN();
      
      std::vector<double> ps;
      ps = std::vector<double>(K, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> log_theta;
      log_theta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(log_theta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 11;
      assign(log_theta, nil_index_list(), stan::math::log(theta),
        "assigning variable log_theta");
      current_statement__ = 12;
      lik = 0;
      current_statement__ = 18;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 15;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 13;
          assign(ps, cons_list(index_uni(k), nil_index_list()),
            (log_theta[(k - 1)] +
              normal_log<false>(z_test[(n - 1)], mu[(k - 1)], sigma[(k - 1)])),
            "assigning variable ps");}
        current_statement__ = 16;
        lik = (lik + log_sum_exp(ps));}
      vars__.emplace_back(lik);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(ps[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(log_theta[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, 1> theta;
      theta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(theta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> theta_flat__;
        current_statement__ = 1;
        assign(theta_flat__, nil_index_list(), context__.vals_r("theta"),
          "assigning variable theta_flat__");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          assign(theta, cons_list(index_uni(sym1__), nil_index_list()),
            theta_flat__[(pos__ - 1)], "assigning variable theta");
          current_statement__ = 1;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> theta_free__;
      theta_free__ = Eigen::Matrix<double, -1, 1>((K - 1));
      stan::math::fill(theta_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      assign(theta_free__, nil_index_list(), stan::math::simplex_free(theta),
        "assigning variable theta_free__");
      Eigen::Matrix<double, -1, 1> mu_prop;
      mu_prop = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(mu_prop, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> mu_prop_flat__;
        current_statement__ = 2;
        assign(mu_prop_flat__, nil_index_list(), context__.vals_r("mu_prop"),
          "assigning variable mu_prop_flat__");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 2;
          assign(mu_prop, cons_list(index_uni(sym1__), nil_index_list()),
            mu_prop_flat__[(pos__ - 1)], "assigning variable mu_prop");
          current_statement__ = 2;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> mu_prop_free__;
      mu_prop_free__ = Eigen::Matrix<double, -1, 1>((K - 1));
      stan::math::fill(mu_prop_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      assign(mu_prop_free__, nil_index_list(),
        stan::math::simplex_free(mu_prop),
        "assigning variable mu_prop_free__");
      double mu_loc;
      mu_loc = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      mu_loc = context__.vals_r("mu_loc")[(1 - 1)];
      double mu_scale;
      mu_scale = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      mu_scale = context__.vals_r("mu_scale")[(1 - 1)];
      double mu_scale_free__;
      mu_scale_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      mu_scale_free__ = stan::math::lb_free(mu_scale, 0);
      std::vector<double> sigma;
      sigma = std::vector<double>(K, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 5;
      assign(sigma, nil_index_list(), context__.vals_r("sigma"),
        "assigning variable sigma");
      std::vector<double> sigma_free__;
      sigma_free__ = std::vector<double>(K, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 5;
        assign(sigma_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(sigma[(sym1__ - 1)], 0),
          "assigning variable sigma_free__");}
      for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        vars__.emplace_back(theta_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
        vars__.emplace_back(mu_prop_free__[(sym1__ - 1)]);}
      vars__.emplace_back(mu_loc);
      vars__.emplace_back(mu_scale_free__);
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        vars__.emplace_back(sigma_free__[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("theta");
    names__.emplace_back("mu_prop");
    names__.emplace_back("mu_loc");
    names__.emplace_back("mu_scale");
    names__.emplace_back("sigma");
    names__.emplace_back("mu");
    names__.emplace_back("lik");
    names__.emplace_back("ps");
    names__.emplace_back("log_theta");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "mu_prop" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "mu_loc");
    param_names__.emplace_back(std::string() + "mu_scale");
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "sigma" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "lik");
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ps" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_theta" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "mu_prop" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "mu_loc");
    param_names__.emplace_back(std::string() + "mu_scale");
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "sigma" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "lik");
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ps" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_theta" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"mu_prop\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"mu_loc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu_scale\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"array\",\"length\":" << K << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"transformed_parameters\"},{\"name\":\"lik\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"ps\",\"type\":{\"name\":\"array\",\"length\":" << K << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_theta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" << (K - 1) << "},\"block\":\"parameters\"},{\"name\":\"mu_prop\",\"type\":{\"name\":\"vector\",\"length\":" << (K - 1) << "},\"block\":\"parameters\"},{\"name\":\"mu_loc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu_scale\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"array\",\"length\":" << K << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"transformed_parameters\"},{\"name\":\"lik\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"ps\",\"type\":{\"name\":\"array\",\"length\":" << K << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_theta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        

};
}

using stan_model = normal_mixture_k_prop_model_namespace::normal_mixture_k_prop_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return normal_mixture_k_prop_model_namespace::profiles__;
}

#endif


