
// Code generated by stanc b0a4f0db
#include <stan/model/model_header.hpp>
namespace flight_simulator_17x463_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 

stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 11, column 2 to column 22)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 12, column 2 to column 28)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 13, column 2 to column 28)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 14, column 2 to column 28)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 15, column 2 to column 26)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 16, column 2 to column 10)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 19, column 2 to column 18)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 21, column 4 to column 61)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 20, column 2 to line 21, column 61)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 26, column 2 to column 26)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 27, column 2 to column 32)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 28, column 2 to column 32)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 30, column 2 to column 22)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 32, column 2 to column 33)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 33, column 2 to column 33)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 38, column 2 to column 27)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 2, column 2 to column 17)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 3, column 2 to column 27)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 4, column 2 to column 25)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 5, column 43 to column 44)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 5, column 2 to column 46)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 6, column 39 to column 40)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 6, column 2 to column 42)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 7, column 9 to column 10)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 7, column 2 to column 14)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 8, column 9 to column 10)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 8, column 2 to column 19)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 14, column 9 to column 20)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 15, column 9 to column 18)",
                                                      " (in 'org/flight_simulator_17.3/flight_simulator_17.3.stan', line 19, column 9 to column 10)"};



class flight_simulator_17x463_model final : public model_base_crtp<flight_simulator_17x463_model> {

 private:
  int N;
  int n_treatment;
  int n_airport;
  std::vector<int> treatment;
  std::vector<int> airport;
  Eigen::Matrix<double, -1, 1> y;
  Eigen::Matrix<double, -1, 1> z_test;
 
 public:
  ~flight_simulator_17x463_model() { }
  
  inline std::string model_name() const final { return "flight_simulator_17x463_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 b0a4f0db", "stancflags = "};
  }
  
  
  flight_simulator_17x463_model(stan::io::var_context& context__,
                                unsigned int random_seed__ = 0,
                                std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "flight_simulator_17x463_model_namespace::flight_simulator_17x463_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 17;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 17;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 17;
      current_statement__ = 17;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 18;
      context__.validate_dims("data initialization","n_treatment","int",
          context__.to_vec());
      n_treatment = std::numeric_limits<int>::min();
      
      current_statement__ = 18;
      n_treatment = context__.vals_i("n_treatment")[(1 - 1)];
      current_statement__ = 18;
      current_statement__ = 18;
      check_greater_or_equal(function__, "n_treatment", n_treatment, 0);
      current_statement__ = 19;
      context__.validate_dims("data initialization","n_airport","int",
          context__.to_vec());
      n_airport = std::numeric_limits<int>::min();
      
      current_statement__ = 19;
      n_airport = context__.vals_i("n_airport")[(1 - 1)];
      current_statement__ = 19;
      current_statement__ = 19;
      check_greater_or_equal(function__, "n_airport", n_airport, 0);
      current_statement__ = 20;
      validate_non_negative_index("treatment", "N", N);
      current_statement__ = 21;
      context__.validate_dims("data initialization","treatment","int",
          context__.to_vec(N));
      treatment = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 21;
      assign(treatment, nil_index_list(), context__.vals_i("treatment"),
        "assigning variable treatment");
      current_statement__ = 21;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 21;
        current_statement__ = 21;
        check_greater_or_equal(function__, "treatment[sym1__]",
                               treatment[(sym1__ - 1)], 0);}
      current_statement__ = 21;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 21;
        current_statement__ = 21;
        check_less_or_equal(function__, "treatment[sym1__]",
                            treatment[(sym1__ - 1)], n_treatment);}
      current_statement__ = 22;
      validate_non_negative_index("airport", "N", N);
      current_statement__ = 23;
      context__.validate_dims("data initialization","airport","int",
          context__.to_vec(N));
      airport = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 23;
      assign(airport, nil_index_list(), context__.vals_i("airport"),
        "assigning variable airport");
      current_statement__ = 23;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 23;
        current_statement__ = 23;
        check_greater_or_equal(function__, "airport[sym1__]",
                               airport[(sym1__ - 1)], 0);}
      current_statement__ = 23;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 23;
        current_statement__ = 23;
        check_less_or_equal(function__, "airport[sym1__]",
                            airport[(sym1__ - 1)], n_airport);}
      current_statement__ = 24;
      validate_non_negative_index("y", "N", N);
      current_statement__ = 25;
      context__.validate_dims("data initialization","y","double",
          context__.to_vec(N));
      y = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(y, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 25;
        assign(y_flat__, nil_index_list(), context__.vals_r("y"),
          "assigning variable y_flat__");
        current_statement__ = 25;
        pos__ = 1;
        current_statement__ = 25;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 25;
          assign(y, cons_list(index_uni(sym1__), nil_index_list()),
            y_flat__[(pos__ - 1)], "assigning variable y");
          current_statement__ = 25;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 26;
      validate_non_negative_index("z_test", "N", N);
      current_statement__ = 27;
      context__.validate_dims("data initialization","z_test","double",
          context__.to_vec(N));
      z_test = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(z_test, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> z_test_flat__;
        current_statement__ = 27;
        assign(z_test_flat__, nil_index_list(), context__.vals_r("z_test"),
          "assigning variable z_test_flat__");
        current_statement__ = 27;
        pos__ = 1;
        current_statement__ = 27;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 27;
          assign(z_test, cons_list(index_uni(sym1__), nil_index_list()),
            z_test_flat__[(pos__ - 1)], "assigning variable z_test");
          current_statement__ = 27;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 28;
      validate_non_negative_index("gamma", "n_treatment", n_treatment);
      current_statement__ = 29;
      validate_non_negative_index("delta", "n_airport", n_airport);
      current_statement__ = 30;
      validate_non_negative_index("y_hat", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += n_treatment;
      num_params_r__ += n_airport;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "flight_simulator_17x463_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      local_scalar_t__ sigma;
      sigma = DUMMY_VAR__;
      
      current_statement__ = 1;
      sigma = in__.scalar();
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        sigma = stan::math::lb_constrain(sigma, 0, lp__);
      } else {
        current_statement__ = 1;
        sigma = stan::math::lb_constrain(sigma, 0);
      }
      local_scalar_t__ sigma_gamma;
      sigma_gamma = DUMMY_VAR__;
      
      current_statement__ = 2;
      sigma_gamma = in__.scalar();
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        sigma_gamma = stan::math::lb_constrain(sigma_gamma, 0, lp__);
      } else {
        current_statement__ = 2;
        sigma_gamma = stan::math::lb_constrain(sigma_gamma, 0);
      }
      local_scalar_t__ sigma_delta;
      sigma_delta = DUMMY_VAR__;
      
      current_statement__ = 3;
      sigma_delta = in__.scalar();
      current_statement__ = 3;
      if (jacobian__) {
        current_statement__ = 3;
        sigma_delta = stan::math::lb_constrain(sigma_delta, 0, lp__);
      } else {
        current_statement__ = 3;
        sigma_delta = stan::math::lb_constrain(sigma_delta, 0);
      }
      Eigen::Matrix<local_scalar_t__, -1, 1> gamma;
      gamma = Eigen::Matrix<local_scalar_t__, -1, 1>(n_treatment);
      stan::math::fill(gamma, DUMMY_VAR__);
      
      current_statement__ = 4;
      gamma = in__.vector(n_treatment);
      Eigen::Matrix<local_scalar_t__, -1, 1> delta;
      delta = Eigen::Matrix<local_scalar_t__, -1, 1>(n_airport);
      stan::math::fill(delta, DUMMY_VAR__);
      
      current_statement__ = 5;
      delta = in__.vector(n_airport);
      local_scalar_t__ mu;
      mu = DUMMY_VAR__;
      
      current_statement__ = 6;
      mu = in__.scalar();
      Eigen::Matrix<local_scalar_t__, -1, 1> y_hat;
      y_hat = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(y_hat, DUMMY_VAR__);
      
      current_statement__ = 9;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 8;
        assign(y_hat, cons_list(index_uni(i), nil_index_list()),
          ((mu + gamma[(treatment[(i - 1)] - 1)]) +
            delta[(airport[(i - 1)] - 1)]), "assigning variable y_hat");}
      {
        current_statement__ = 10;
        lp_accum__.add(uniform_lpdf<propto__>(sigma, 0, 100));
        current_statement__ = 11;
        lp_accum__.add(uniform_lpdf<propto__>(sigma_gamma, 0, 100));
        current_statement__ = 12;
        lp_accum__.add(uniform_lpdf<propto__>(sigma_delta, 0, 100));
        current_statement__ = 13;
        lp_accum__.add(normal_lpdf<propto__>(mu, 0, 100));
        current_statement__ = 14;
        lp_accum__.add(normal_lpdf<propto__>(gamma, 0, sigma_gamma));
        current_statement__ = 15;
        lp_accum__.add(normal_lpdf<propto__>(delta, 0, sigma_delta));
        current_statement__ = 16;
        lp_accum__.add(normal_lpdf<propto__>(y, y_hat, sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "flight_simulator_17x463_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      sigma = in__.scalar();
      current_statement__ = 1;
      sigma = stan::math::lb_constrain(sigma, 0);
      double sigma_gamma;
      sigma_gamma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      sigma_gamma = in__.scalar();
      current_statement__ = 2;
      sigma_gamma = stan::math::lb_constrain(sigma_gamma, 0);
      double sigma_delta;
      sigma_delta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      sigma_delta = in__.scalar();
      current_statement__ = 3;
      sigma_delta = stan::math::lb_constrain(sigma_delta, 0);
      Eigen::Matrix<double, -1, 1> gamma;
      gamma = Eigen::Matrix<double, -1, 1>(n_treatment);
      stan::math::fill(gamma, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      gamma = in__.vector(n_treatment);
      Eigen::Matrix<double, -1, 1> delta;
      delta = Eigen::Matrix<double, -1, 1>(n_airport);
      stan::math::fill(delta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 5;
      delta = in__.vector(n_airport);
      double mu;
      mu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      mu = in__.scalar();
      Eigen::Matrix<double, -1, 1> y_hat;
      y_hat = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(y_hat, std::numeric_limits<double>::quiet_NaN());
      
      vars__.emplace_back(sigma);
      vars__.emplace_back(sigma_gamma);
      vars__.emplace_back(sigma_delta);
      for (int sym1__ = 1; sym1__ <= n_treatment; ++sym1__) {
        vars__.emplace_back(gamma[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_airport; ++sym1__) {
        vars__.emplace_back(delta[(sym1__ - 1)]);}
      vars__.emplace_back(mu);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 9;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 8;
        assign(y_hat, cons_list(index_uni(i), nil_index_list()),
          ((mu + gamma[(treatment[(i - 1)] - 1)]) +
            delta[(airport[(i - 1)] - 1)]), "assigning variable y_hat");}
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          vars__.emplace_back(y_hat[(sym1__ - 1)]);}
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      double sigma_free__;
      sigma_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      sigma_free__ = stan::math::lb_free(sigma, 0);
      double sigma_gamma;
      sigma_gamma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      sigma_gamma = context__.vals_r("sigma_gamma")[(1 - 1)];
      double sigma_gamma_free__;
      sigma_gamma_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      sigma_gamma_free__ = stan::math::lb_free(sigma_gamma, 0);
      double sigma_delta;
      sigma_delta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      sigma_delta = context__.vals_r("sigma_delta")[(1 - 1)];
      double sigma_delta_free__;
      sigma_delta_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      sigma_delta_free__ = stan::math::lb_free(sigma_delta, 0);
      Eigen::Matrix<double, -1, 1> gamma;
      gamma = Eigen::Matrix<double, -1, 1>(n_treatment);
      stan::math::fill(gamma, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> gamma_flat__;
        current_statement__ = 4;
        assign(gamma_flat__, nil_index_list(), context__.vals_r("gamma"),
          "assigning variable gamma_flat__");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= n_treatment; ++sym1__) {
          current_statement__ = 4;
          assign(gamma, cons_list(index_uni(sym1__), nil_index_list()),
            gamma_flat__[(pos__ - 1)], "assigning variable gamma");
          current_statement__ = 4;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> delta;
      delta = Eigen::Matrix<double, -1, 1>(n_airport);
      stan::math::fill(delta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> delta_flat__;
        current_statement__ = 5;
        assign(delta_flat__, nil_index_list(), context__.vals_r("delta"),
          "assigning variable delta_flat__");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= n_airport; ++sym1__) {
          current_statement__ = 5;
          assign(delta, cons_list(index_uni(sym1__), nil_index_list()),
            delta_flat__[(pos__ - 1)], "assigning variable delta");
          current_statement__ = 5;
          pos__ = (pos__ + 1);}
      }
      double mu;
      mu = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      mu = context__.vals_r("mu")[(1 - 1)];
      vars__.emplace_back(sigma_free__);
      vars__.emplace_back(sigma_gamma_free__);
      vars__.emplace_back(sigma_delta_free__);
      for (int sym1__ = 1; sym1__ <= n_treatment; ++sym1__) {
        vars__.emplace_back(gamma[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_airport; ++sym1__) {
        vars__.emplace_back(delta[(sym1__ - 1)]);}
      vars__.emplace_back(mu);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("sigma");
    names__.emplace_back("sigma_gamma");
    names__.emplace_back("sigma_delta");
    names__.emplace_back("gamma");
    names__.emplace_back("delta");
    names__.emplace_back("mu");
    names__.emplace_back("y_hat");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_treatment)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_airport)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "sigma_gamma");
    param_names__.emplace_back(std::string() + "sigma_delta");
    for (int sym1__ = 1; sym1__ <= n_treatment; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "gamma" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= n_airport; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "delta" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "mu");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_hat" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "sigma_gamma");
    param_names__.emplace_back(std::string() + "sigma_delta");
    for (int sym1__ = 1; sym1__ <= n_treatment; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "gamma" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= n_airport; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "delta" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "mu");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_hat" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_gamma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_delta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" << n_treatment << "},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"vector\",\"length\":" << n_airport << "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_hat\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_gamma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_delta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" << n_treatment << "},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"vector\",\"length\":" << n_airport << "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_hat\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        

};
}

using stan_model = flight_simulator_17x463_model_namespace::flight_simulator_17x463_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return flight_simulator_17x463_model_namespace::profiles__;
}

#endif


