
// Code generated by stanc b0a4f0db
#include <stan/model/model_header.hpp>
namespace wells_dae_new_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 

stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 16, column 2 to column 17)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 24, column 0 to column 9)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 25, column 0 to column 8)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 27, column 4 to column 157)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 26, column 23 to line 28, column 1)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 26, column 0 to line 28, column 1)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 19, column 2 to line 21, column 48)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 2, column 2 to column 17)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 3, column 32 to column 33)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 3, column 2 to column 35)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 4, column 9 to column 10)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 4, column 2 to column 17)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 5, column 9 to column 10)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 5, column 2 to column 20)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 6, column 9 to column 10)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 6, column 2 to column 17)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 7, column 13 to column 14)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 7, column 2 to column 16)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 10, column 9 to column 10)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 10, column 2 to column 20)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 11, column 9 to column 10)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 11, column 2 to column 18)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 12, column 2 to column 26)",
                                                      " (in 'org/wells_dae/wells_dae_new.stan', line 13, column 2 to column 24)"};



class wells_dae_new_model final : public model_base_crtp<wells_dae_new_model> {

 private:
  int N;
  std::vector<int> switched;
  Eigen::Matrix<double, -1, 1> dist;
  Eigen::Matrix<double, -1, 1> arsenic;
  Eigen::Matrix<double, -1, 1> educ;
  std::vector<int> z_test;
  Eigen::Matrix<double, -1, 1> dist100;
  Eigen::Matrix<double, -1, 1> educ4;
 
 public:
  ~wells_dae_new_model() { }
  
  inline std::string model_name() const final { return "wells_dae_new_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 b0a4f0db", "stancflags = "};
  }
  
  
  wells_dae_new_model(stan::io::var_context& context__,
                      unsigned int random_seed__ = 0,
                      std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "wells_dae_new_model_namespace::wells_dae_new_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 8;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 8;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 8;
      current_statement__ = 8;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 9;
      validate_non_negative_index("switched", "N", N);
      current_statement__ = 10;
      context__.validate_dims("data initialization","switched","int",
          context__.to_vec(N));
      switched = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 10;
      assign(switched, nil_index_list(), context__.vals_i("switched"),
        "assigning variable switched");
      current_statement__ = 10;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 10;
        current_statement__ = 10;
        check_greater_or_equal(function__, "switched[sym1__]",
                               switched[(sym1__ - 1)], 0);}
      current_statement__ = 10;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 10;
        current_statement__ = 10;
        check_less_or_equal(function__, "switched[sym1__]",
                            switched[(sym1__ - 1)], 1);}
      current_statement__ = 11;
      validate_non_negative_index("dist", "N", N);
      current_statement__ = 12;
      context__.validate_dims("data initialization","dist","double",
          context__.to_vec(N));
      dist = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(dist, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> dist_flat__;
        current_statement__ = 12;
        assign(dist_flat__, nil_index_list(), context__.vals_r("dist"),
          "assigning variable dist_flat__");
        current_statement__ = 12;
        pos__ = 1;
        current_statement__ = 12;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 12;
          assign(dist, cons_list(index_uni(sym1__), nil_index_list()),
            dist_flat__[(pos__ - 1)], "assigning variable dist");
          current_statement__ = 12;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 13;
      validate_non_negative_index("arsenic", "N", N);
      current_statement__ = 14;
      context__.validate_dims("data initialization","arsenic","double",
          context__.to_vec(N));
      arsenic = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(arsenic, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> arsenic_flat__;
        current_statement__ = 14;
        assign(arsenic_flat__, nil_index_list(), context__.vals_r("arsenic"),
          "assigning variable arsenic_flat__");
        current_statement__ = 14;
        pos__ = 1;
        current_statement__ = 14;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 14;
          assign(arsenic, cons_list(index_uni(sym1__), nil_index_list()),
            arsenic_flat__[(pos__ - 1)], "assigning variable arsenic");
          current_statement__ = 14;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 15;
      validate_non_negative_index("educ", "N", N);
      current_statement__ = 16;
      context__.validate_dims("data initialization","educ","double",
          context__.to_vec(N));
      educ = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(educ, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> educ_flat__;
        current_statement__ = 16;
        assign(educ_flat__, nil_index_list(), context__.vals_r("educ"),
          "assigning variable educ_flat__");
        current_statement__ = 16;
        pos__ = 1;
        current_statement__ = 16;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 16;
          assign(educ, cons_list(index_uni(sym1__), nil_index_list()),
            educ_flat__[(pos__ - 1)], "assigning variable educ");
          current_statement__ = 16;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 17;
      validate_non_negative_index("z_test", "N", N);
      current_statement__ = 18;
      context__.validate_dims("data initialization","z_test","int",
          context__.to_vec(N));
      z_test = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 18;
      assign(z_test, nil_index_list(), context__.vals_i("z_test"),
        "assigning variable z_test");
      current_statement__ = 19;
      validate_non_negative_index("dist100", "N", N);
      current_statement__ = 20;
      dist100 = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(dist100, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 21;
      validate_non_negative_index("educ4", "N", N);
      current_statement__ = 22;
      educ4 = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(educ4, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 23;
      assign(dist100, nil_index_list(), divide(dist, 100.0),
        "assigning variable dist100");
      current_statement__ = 24;
      assign(educ4, nil_index_list(), divide(educ, 4.0),
        "assigning variable educ4");
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 4;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "wells_dae_new_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> beta;
      beta = Eigen::Matrix<local_scalar_t__, -1, 1>(4);
      stan::math::fill(beta, DUMMY_VAR__);
      
      current_statement__ = 1;
      beta = in__.vector(4);
      {
        current_statement__ = 7;
        lp_accum__.add(
          bernoulli_logit_lpmf<propto__>(switched,
            add(
              add(add(beta[(1 - 1)], multiply(beta[(2 - 1)], dist100)),
                multiply(beta[(3 - 1)], arsenic)),
              multiply(beta[(4 - 1)], educ4))));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "wells_dae_new_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(4);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      beta = in__.vector(4);
      for (int sym1__ = 1; sym1__ <= 4; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      double lik;
      lik = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      lik = 0;
      current_statement__ = 6;
      for (int observe_i = 1; observe_i <= N; ++observe_i) {
        current_statement__ = 4;
        lik = (lik +
                bernoulli_logit_lpmf<false>(z_test[(observe_i - 1)],
                  (((beta[(1 - 1)] +
                      (beta[(2 - 1)] * dist100[(observe_i - 1)])) +
                     (beta[(3 - 1)] * arsenic[(observe_i - 1)])) +
                    (beta[(4 - 1)] * educ4[(observe_i - 1)]))));}
      vars__.emplace_back(lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(4);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 1;
        assign(beta_flat__, nil_index_list(), context__.vals_r("beta"),
          "assigning variable beta_flat__");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= 4; ++sym1__) {
          current_statement__ = 1;
          assign(beta, cons_list(index_uni(sym1__), nil_index_list()),
            beta_flat__[(pos__ - 1)], "assigning variable beta");
          current_statement__ = 1;
          pos__ = (pos__ + 1);}
      }
      for (int sym1__ = 1; sym1__ <= 4; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("beta");
    names__.emplace_back("lik");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(4)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= 4; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "lik");
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= 4; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "lik");
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << 4 << "},\"block\":\"parameters\"},{\"name\":\"lik\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << 4 << "},\"block\":\"parameters\"},{\"name\":\"lik\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        

};
}
using stan_model = wells_dae_new_model_namespace::wells_dae_new_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return wells_dae_new_model_namespace::profiles__;
}

#endif


